# 插件基本信息
name: "example-deployer"
display_name: "示例部署器"
description: "这是一个插件开发示例，展示如何创建自定义部署组件"
version: "1.0.0"
author: "CertM Team"
homepage: "https://github.com/certm/example-deployer"
license: "MIT"

# 组件信息
component:
  type: "deploy"
  category: "example"
  tags: ["example", "demo", "template"]

# 兼容性
compatibility:
  min_engine_version: "1.0.0"
  max_engine_version: "2.0.0"
  platforms:
    - os: "linux"
      arch: "amd64"
    - os: "linux"
      arch: "arm64"

# 依赖
dependencies:
  - name: "certm-plugin-sdk"
    version: "^1.0.0"

# 权限需求
permissions:
  network:
    - "*.example.com"
  storage:
    read: ["config", "temp"]
    write: ["temp", "logs"]

# 资源限制
resources:
  max_memory_mb: 256
  max_cpu_percent: 30
  timeout_seconds: 300

# 市场信息
market:
  price: 0
  changelog: |
    ## v1.0.0
    - 初始版本
    - 基础部署功能

